root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/app.exe"
  bin = "tmp/app.exe"
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp", "vendor"]
  send_interrupt = false
  kill_delay = "0s"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true

[log]
  time = true
